"""Add article analyses

Revision ID: c95fe2ff215e
Revises: 611729d11fa8
Create Date: 2026-07-31 14:51:56.261791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95fe2ff215e'
down_revision = '611729d11fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=150), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('technologies_json', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_analyses_article_id'), ['article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_analyses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_article_analyses_article_id'))

    op.drop_table('article_analyses')
    # ### end Alembic commands ###
